# Generated by Django 3.2.4 on 2021-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_num', models.CharField(max_length=50, null=True, verbose_name='企业编号')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='企业名称')),
                ('pos', models.CharField(max_length=50, null=True, verbose_name='职位')),
                ('hiring', models.CharField(max_length=50, null=True, verbose_name='人数')),
                ('edu_bgd', models.CharField(max_length=50, null=True, verbose_name='学历')),
                ('major', models.CharField(max_length=50, null=True, verbose_name='专业')),
                ('salary', models.CharField(max_length=500, null=True, verbose_name='工资')),
                ('en', models.CharField(max_length=50, null=True, verbose_name='英语')),
                ('job_des', models.CharField(max_length=50, null=True, verbose_name='职位描述')),
            ],
        ),
        migrations.CreateModel(
            name='enterprise_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_num', models.CharField(max_length=50, null=True, verbose_name='企业编号')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='企业名称')),
                ('ent_property', models.CharField(max_length=50, null=True, verbose_name='企业性质')),
                ('time_est', models.CharField(max_length=50, null=True, verbose_name='成立时间')),
                ('num_em', models.CharField(max_length=50, null=True, verbose_name='员工人数')),
                ('reg_cap', models.CharField(max_length=50, null=True, verbose_name='注册资金')),
                ('ent_abstract', models.CharField(max_length=500, null=True, verbose_name='简介')),
            ],
        ),
    ]
