# Generated by Django 3.2.4 on 2021-07-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgroup',
            options={'verbose_name': '聊天组', 'verbose_name_plural': '聊天组'},
        ),
    ]
