# Generated by Django 3.2.4 on 2021-06-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('banji', models.CharField(max_length=32, null=True, verbose_name='班级')),
                ('baokao_school', models.CharField(max_length=32, null=True, verbose_name='报考院校')),
                ('luqu_yuanbu', models.CharField(max_length=32, null=True, verbose_name='录取院部')),
                ('luqu_zhuanye', models.CharField(max_length=32, null=True, verbose_name='录取专业')),
                ('paiming', models.CharField(max_length=32, null=True, verbose_name='排名')),
            ],
        ),
        migrations.CreateModel(
            name='stu17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('banji', models.CharField(max_length=32, null=True, verbose_name='班级')),
                ('baokao_school', models.CharField(max_length=32, null=True, verbose_name='报考院校')),
                ('luqu_yuanbu', models.CharField(max_length=32, null=True, verbose_name='录取院部')),
                ('luqu_zhuanye', models.CharField(max_length=32, null=True, verbose_name='录取专业')),
                ('leixing', models.CharField(max_length=32, null=True, verbose_name='工作类型')),
            ],
        ),
        migrations.CreateModel(
            name='Student_luhao_shanjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('gender', models.CharField(max_length=32, null=True, verbose_name='性别')),
                ('major', models.CharField(max_length=32, null=True, verbose_name='专业')),
                ('departments', models.CharField(max_length=32, null=True, verbose_name='院系')),
                ('education_background', models.CharField(max_length=32, null=True, verbose_name='学历')),
                ('ruxue_year', models.CharField(max_length=32, null=True, verbose_name='年度')),
                ('Cultivating_way', models.CharField(max_length=32, null=True, verbose_name='培养方式')),
                ('kaoqu_yuanxi', models.CharField(max_length=32, null=True, verbose_name='考取院系')),
                ('kaoqu_zhuaye', models.CharField(max_length=32, null=True, verbose_name='考取专业')),
                ('xuezhi', models.CharField(max_length=32, null=True, verbose_name='学制')),
                ('danwei_location', models.CharField(max_length=32, null=True, verbose_name='单位所在地')),
                ('danwei', models.CharField(max_length=32, null=True, verbose_name='单位')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
