# Generated by Django 3.2.4 on 2021-07-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_userinfo_flag'),
    ]

    operations = [
    ]
