# Generated by Django 3.2.4 on 2021-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_auto_20210711_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_jiuye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('gender', models.CharField(max_length=32, null=True, verbose_name='性别')),
                ('major', models.CharField(max_length=32, null=True, verbose_name='专业')),
                ('departments', models.CharField(max_length=32, null=True, verbose_name='院系')),
                ('education_background', models.CharField(max_length=32, null=True, verbose_name='学历')),
                ('ruxue_year', models.CharField(max_length=32, null=True, verbose_name='年度')),
                ('Cultivating_way', models.CharField(max_length=32, null=True, verbose_name='培养方式')),
                ('xuezhi', models.CharField(max_length=32, null=True, verbose_name='学制')),
                ('danwei_location', models.CharField(max_length=32, null=True, verbose_name='单位所在地')),
                ('danwei', models.CharField(max_length=32, null=True, verbose_name='单位')),
                ('jieyue', models.CharField(max_length=32, null=0, verbose_name='解约')),
            ],
        ),
    ]
