# Generated by Django 3.2.4 on 2021-07-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_stu_jiuye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_jiuye',
            name='jieyue',
        ),
    ]
