# Generated by Django 3.2.4 on 2021-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_remove_stu_jiuye_jieyue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_jiuye',
            name='jieyue',
            field=models.CharField(default=0, max_length=32, verbose_name='解约'),
        ),
    ]
