# Generated by Django 3.2.4 on 2021-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_stu_jiuye_jieyue'),
    ]

    operations = [
        migrations.CreateModel(
            name='jieyue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ter_time', models.CharField(max_length=50, null=True, verbose_name='解约时间')),
                ('ter_ed', models.CharField(max_length=50, null=True, verbose_name='被解约人')),
                ('ter_user', models.CharField(max_length=50, null=True, verbose_name='解约操作人')),
                ('ter_ing', models.CharField(max_length=50, null=True, verbose_name='解约方')),
                ('ter_reason', models.CharField(max_length=50, null=True, verbose_name='解约原因')),
                ('ter_note', models.CharField(max_length=500, null=True, verbose_name='解约备注')),
                ('ter_compensation', models.CharField(max_length=50, null=True, verbose_name='解约赔偿')),
            ],
        ),
    ]
