# Generated by Django 3.2.4 on 2021-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_jieyue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jieyue',
            name='ter_id',
            field=models.CharField(max_length=50, null=True, verbose_name='被解约人xuehao'),
        ),
    ]
