# Generated by Django 3.2.4 on 2021-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_jieyue_ter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jieyue',
            name='ter_id',
            field=models.CharField(max_length=50, null=True, verbose_name='被解约人学号'),
        ),
    ]
